### ISSUE TITLE
where exactly are your extended features?

### ISSUE THREAD

**Issue by akhoury** [DiegoRBaquero/node-os#1]
am I missing something? or you're just exporting the native `os` module. 
```
module.exports = require('os')
```
https://github.com/DiegoRBaquero/node-aos/blob/58876ff358aae5a2c112fc04e3ebf51f93a7ba3c/index.js#L1

do you plans to extend this? if i may suggest adding something like
* `mempercpu()` how much memory each cpu is using

**Comment by DiegoRBaquero** [comment]
That was certainly my intention, yes, but I never really worked on this features due to lacking time.

Feel free to submit any you'd like as a PR :)
