### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by MediFlexDev** [DiegoRBaquero/node-os#6]
[
![image](https://user-images.githubusercontent.com/42582303/136248485-caadc476-3dc6-459f-879b-647ed2ebd539.png)
](url)

![image](https://user-images.githubusercontent.com/42582303/136248511-e0085479-018b-4883-bb27-a8d9a95c3ccd.png)

**Comment by MediFlexDev** [comment]
wait huh what is this repo

**Comment by DiegoRBaquero** [comment]
This is just a package wrapper of Node's core `os` module, should probably report in Node's repo :)
